# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef8354de631868820fdc27257600052f"
name = "Loyalty Program waro"
application_url = "https://loyalty-program-9jqr.vercel.app/api/shopify/authenticate"
embedded = false
handle = "loyalty-program-waro"

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,write_customers,write_content,read_content,read_products,write_products,write_files,read_files,write_online_store_navigation,read_online_store_navigation,write_publications,read_publications,write_product_listings,read_product_listings"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://loyalty-program-9jqr.vercel.app/api/shopify/authenticate",
  "https://loyalty-program-9jqr.vercel.app/api/shopify/callback"
]
